/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_rtln_defense_JniEducation */

#ifndef _Included_ru_rtln_defense_JniEducation
#define _Included_ru_rtln_defense_JniEducation
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     ru_rtln_defense_JniEducation
	 * Method:    print
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_ru_rtln_defense_JniEducation_print
	(JNIEnv*, jobject);

	/*
	 * Class:     ru_rtln_defense_JniEducation
	 * Method:    getLine
	 * Signature: (Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_ru_rtln_defense_JniEducation_getLine
	(JNIEnv*, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
